=== aroago/2021_LMSGI_AGO/EX02_20210309_aroaGraneroOmañas/mapaestelar.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT mapaEstelar (constelacion|estrella)?>
<!ATTLIST mapaEstelar
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED>
<!ELEMENT constelacion (Nombre_Español,superficie,estrellas,objetos,colindantes,observacion)>
<!ATTLIST constelacion
    nombreLatin CDATA #REQUIRED>
<!ELEMENT Nombre_Español (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterismo,masBrillante)>
<!ATTLIST estrellas
    num_estre CDATA #IMPLIED>
<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masBrillante (#PCDATA)>
<!ATTLIST masBrillante
    luminosidad CDATA #IMPLIED>
<!ELEMENT objetos (cumulos,nebulosas,galaxias,cuasares,lluviaMeteoros+)>
<!ELEMENT cumulos (#PCDATA)>
<!ELEMENT nebulosas (#PCDATA)>
<!ELEMENT galaxias (#PCDATA)>
<!ELEMENT cuasares (#PCDATA)>
<!ELEMENT lluviaMeteoros (#PCDATA)>
<!ELEMENT colindantes (nombre*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT observacion (hemisferio,mes,hora)>
<!ELEMENT hemisferio (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT hora (#PCDATA)>

<!ELEMENT estrella (nombre,constelacion,distancia,luminosidad,temperatura,masa)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia
    unidadM CDATA #FIXED "años Luz">
<!ELEMENT luminosidad (#PCDATA)>
<!ATTLIST luminosidad
    medida CDATA #FIXED "soles">
<!ELEMENT temperatura (#PCDATA)>
<!ATTLIST temperatura
    medida CDATA #FIXED "K">
<!ELEMENT masa (#PCDATA)>
<!ATTLIST masa
    medida CDATA "soles">

=== aroago/2021_LMSGI_AGO/EX02_20210309_aroaGraneroOmañas/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE mapaEstelar SYSTEM 'mapaestelar.dtd'>
<mapaEstelar xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
           xsi:noNamespaceSchemaLocation='mapaestelar.xsd'>
    <constelacion nombreLatin="ursa Maior">
        <Nombre_Español>Osa Mayor</Nombre_Español>
        <superficie>1279,7</superficie>
        <estrellas num_estre="209">
            <asterismo>7</asterismo>
            <masBrillante luminosidad="1,77">Alion</masBrillante>
        </estrellas>
        <objetos>
            <cumulos>false</cumulos>
            <nebulosas>true</nebulosas>
            <galaxias>true</galaxias>
            <cuasares>false</cuasares>
            <lluviaMeteoros>Kappa Ursa Mayoridas</lluviaMeteoros>
            <lluviaMeteoros>Lamba Ursa Mayoridas</lluviaMeteoros>
            <lluviaMeteoros>Psi Ursa Mayoritaria</lluviaMeteoros>
        </objetos>
        <colindantes>
            <nombre>Bootes</nombre>
            <nombre>Camelopardalis</nombre>
            <nombre>Draco</nombre>
            <nombre>Leo</nombre>
            <nombre>Lynx</nombre>
        </colindantes>
        <observacion>
            <hemisferio>Norte</hemisferio>
            <mes>04</mes>
            <hora>21:00:00</hora>
        </observacion>
    </constelacion>
</mapaEstelar>
