=== aroago/2021_LMSGI_AGO/ud04/04_12.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT receta (nombre,descripcion,tiempo,ingredientes,instrucciones)>
<!ATTLIST receta
        plato (primero|segundo|postre) #REQUIRED
        xsi:noNamespaceSchemaLocation CDATA #IMPLIED
        xmlns:xsi CDATA #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ATTLIST tiempo
        preparacion CDATA #REQUIRED
        coccion CDATA #IMPLIED>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (nombre,cantidad?)>
<!ELEMENT nombrei (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST cantidad
         unidad (gramos|pizca|mililitros|cucharada|chorro) #IMPLIED>
<!ELEMENT instrucciones (paso+)>
<!ELEMENT paso (#PCDATA)>

=== aroago/2021_LMSGI_AGO/ud04/04_12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE receta SYSTEM '04_12.dtd'>
<receta plato="primero" xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='04_12.xsd'>
    <nombre>Rissoto milanesa</nombre>
    <descripcion>receta de 20 min</descripcion>
    <tiempo preparacion="" coccion="20">min</tiempo>
    <ingredientes>
        <ingrediente>
            <nombre>arroz</nombre>
            <cantidad unidad="gramos">500</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>cebolla</nombre>
            <cantidad>1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>azafran</nombre>
            <cantidad unidad="pizca">1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>queso parmesano</nombre>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Sal</nombre>
        </ingrediente>
        <ingrediente>
            <nombre>Pimienta</nombre>
        </ingrediente>
        <ingrediente>
            <nombre>caldo</nombre>
            <cantidad unidad="mililitros">1000</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>vino blanco</nombre>
            <cantidad unidad="chorro">1</cantidad>
        </ingrediente>
    </ingredientes>
    <instrucciones>
        <paso>Picamos la cebolla y la pochamos con la mitad
        de la mantequilla.</paso>
        <paso>Cuando este transparente,echamos el azafran,
        el vino y dejamos que reduzca.</paso>
        <paso>A continuacion, incorporamos el arroz,
        lo sofreimos un poco.</paso>
        <paso>Vamos anadiendo el caldo caliente poco a poco
        mientras removemos</paso>
        <paso>Salpimentamos.</paso>
        <paso>Caundo este casi hecho, agregamos el resto de 
        la mantequilla y el queso</paso>
        <paso>Servimos enseguida.</paso>
    </instrucciones>
</receta>
