=== aroago/2021_LMSGI_AGO/ud04/04_11.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:simpleType name="tipoMedida">
        <xs:restriction base="xs:string">
            <xs:pattern value="Mb|Gb|Tb"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="portatil" minOccurs="0" maxOccurs="unbouned">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="referencia">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{2}[0-9]{5}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nombre" type="xs:String"></xs:element>
                            <xs:element name="fabricante">
                                <xs:complexType>
                                    <xs:atribute name="nombre"  use="required">
                                        <xs:simpleTipe base="string">
                                            <xs:pattern value="LENOVO|HP|MSI|APPLE|ASUS|DELL|DESCONOCIDO"/>
                                        </xs:simpleTipe>
                                    </xs:atribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="procesador">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombreP" type="xs:string"/>
                                        <xs:element name="cache">
                                            <xs:complexType>
                                                <xs:extension base="xs:positiveInteger">
                                                    <xs:attribute name="tamanyo" type="xs:string" default="Gb"/>
                                                </xs:extension>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="numero" type="xs:byte"></xs:element>
                                        <xs:element name="velocidad" Type="xs:float" ></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ram">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="memoria">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:">
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tipo" tipo=""/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="disco">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:positiveInteger">
                                             <xs:attribute name="tipo" type="xs:string"/>
                                                <xs:attribute name="media" type="xs:string" default="Gb"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="pantalla">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dimension" type="xs:string"/>
                                        <xs:element name="resolucion" type="xs:string"/>
                                        <xs:element name="maxima" type="xs:string" minOccurs="0"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="grafica" type="xs:string"/>
                            <xs:element name="foto" type="xs:image/jpg" maxOccurs="unbouned"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>       
</xs:schema>

=== aroago/2021_LMSGI_AGO/ud04/04_11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
@author Aroa Granero Omanas
@Fecha_de_modificacion:24/02/2021
@Contenido: Diseña un lenguaje XML que almacenen información sobre un catalogo de productos, 
en él se guarda las características de los portátiles.
-->
<!DOCTYPE catalogo SYSTEM '04_11.dtd'>
<catalogo xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='04_11.xsd'>
    <portatil>
        <referencia>HP10219</referencia>
        <nombre>PORTATIL HP 15-DA0204NS</nombre>
        <fabricante nombre="HP"/>
        <procesador>
            <nombreP>CORE I3-7020U</nombreP>
            <cache tamanyo="Mb"></cache>
            <n_Procesadores></n_Procesadores>
            <velocidad medida="GHz">2,3GHZ</velocidad>
        </procesador>
        <ram>
            <memoria unidad_de_medida="Gb">8GB</memoria>
            <tipo>DDR3</tipo>
        </ram>
        <disco capacidad="Gb">256Gb SSD</disco>
        <pantalla>
            <dimension>15.6 pulgadas</dimension>
            <resolucion>1266x768</resolucion>
            <resolucion_max>1366x768</resolucion_max>
        </pantalla>
        <grafica>UHD Graphics 620</grafica>
        <fotos>foto1.png</fotos>
    </portatil>
    <portatil>
        <referencia></referencia>
        <nombre>PORTATIL LENOVO IDEAPAD</nombre>
        <fabricante nombre="LENOVO"/>
        <procesador>
            <nombreP>S145 CORE I3-8145U</nombreP>
            <cache tamanyo="Gb"></cache>
            <n_Procesadores></n_Procesadores>
            <velocidad medida="GHz">2,1GHZ</velocidad>
        </procesador>
        <ram>
            <memoria unidad_de_medida="Gb">8GB</memoria>
            <tipo>DDR3</tipo>
        </ram>
         <disco capacidad="Gb">256Gb SSD</disco>
        <pantalla>
            <dimension>15.6 pulgadas</dimension>
            <resolucion>1266x768</resolucion>
        </pantalla>
        <grafica>UHD Graphics 620</grafica>
        <fotos>foto2.png</fotos>
        <fotos>foto3.png</fotos>
    </portatil>
</catalogo>
