<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email [
    <!ELEMENT remitente (#PCDATA)>
    <!ELEMENT destinatario (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT mensaje (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT fecha (dia,mes,anyo)>
    <!ELEMENT ficherosAdj (nombre, tipo)>
    <!ELEMENT email (remitente, destinatario+, fecha, asunto?, mensaje?, ficherosAdj*)>
]>
<email
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='04_1.xsd'>>
	<remitente>miCasa@gmail.com</remitente>
	<destinatario>MiMansion@gmail.com</destinatario>
        <destinatario>MiChale@gmail.com</destinatario>
	<fecha>
            <dia>19</dia>
            <mes>06</mes>
            <anyo>2021</anyo>
        </fecha>
	<asunto>Me mudo de casa</asunto>
	<mensaje/>
	<ficherosAdj>
		<nombre>Aroa.pdf</nombre>
		<tipo>application/pdf</tipo>
	</ficherosAdj>
        <ficherosAdj>
		<nombre>imagen.png</nombre>
		<tipo>image/png</tipo>
	</ficherosAdj>
</email>

