=== aroago/2021_LMSGI_AGO/ud04/04_3.dtd
<!ELEMENT descipcion (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT fecha (dia,mes,ano)>
<!ELEMENT evento (descripcion, fecha)>
<!ELEMENT hechosHistoricos (evento+)>

=== aroago/2021_LMSGI_AGO/ud04/04_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hechosHistoricos SYSTEM '04_3.dtd'>

<hechosHistoricos xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='04_3.xsd'>
    <evento>
        <descripcion>Se Funda YouTube</descripcion>
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <ano>2005</ano>
        </fecha>
    </evento>
    <evento>
        <descripcion>Se Funda Google</descripcion>
        <fecha>
            <dia>5</dia>
            <mes>9</mes>
            <ano>1998</ano>
        </fecha>
    </evento>
    <evento>
        <descripcion>Se Funda Facebook</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <ano>2004</ano>
        </fecha>
    </evento>
</hechosHistoricos>
